language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: npm
  email: deployment@dhis2.org
  api_key:
    secure: cwIDNUWmN+Guwo3oi2R6iFbUWIJ2wltgrWSIOleqCQJi4hUQnyufxcafO5sM8+e+W52esVL6q3C46pL8LPVoG0NYP36LqaXpx+3TaS3t6/Mj7Q2/yBo90giM8S5NFh4GsPHJu7YpagbzkCtZDodOHCQRREDhGvovMVlg9LCcgym+oBpLR1vZL2nbFqF3d7uP68liHQV27pVWXxmBZ1Ad0ZYaGkjDQKMNYy+RA4fZfpAiL8iK8nG9jeqVkAVFpDOhA3uYrnu0dLGuI30jOjZwKSPb49Rzg2bPL0LgwbDFcpRoMrrash4vfRhR4cEc0CpVOl2xnESX9ATRzGA92KC/CpyhGxFFmInTvtbae2DBCgSEWXbqo5MTySzCtDjvSPSsiPLoVhfqNZrUO7SNUS9cyylNlK8lCrRAkbPRe+WWJXLm1CVdAljdh/yHiRgazIBmgfIO1Nw7sxCQ9M6Mn/5UbDVvMLtqOMtnFrW6R8FhhvKFGp+XCrQ24xbc6td69TWSpljW/3GWKCuVYYurvqd6OvQLrLpbf0+R11yHJbLmhVsSDE1Dj9znKUOFDCUNraw8/FZQ/gQRRcmTsA0oxMj0HGoLsy3tfYLQeRgd/lknWFgCoHOnSVn02rw9BfBwMReAFhnKdKnzX6XoZpwM+Bni4Jk8J+YLNuDllQZ5uD/rylc=
  skip_cleanup: true
  on:
    tags: true
    repo: dhis2/d2-analysis
